### ISSUE TITLE
Custom README

### ISSUE THREAD

**Issue by mxstbr** [kevindavus/personal-goals-cli#1]
Right now, the CLI replaces the full README every time a change is requested and inserts the change in the new content. This means I can't change the boilerplate content of the README, since it's just going to revert back to the initial state when I change/add/remove a goal.

Instead, the first time the CLI is run and the README would be adapted it should create a new README based on the template, with a small change: it has invisible markers for goals. Something like this:

```markdown

Personal Goals
==============
Personal goals made open source for accessibility across computers I use, transparency, accountability, and versioning. Learn more about it [here](http://una.im/personal-goals-guide).

# Overarching Goals for 2017:
### This year's focus: Do good things this year

  
<!-- personal-goals-cli yearly -->
  
# Weekly Goals Aug 27th, 2017:
### This week's focus: Do good things this week

<!-- personal-goals-cli weekly -->

# Monthly Goals August 2017:
### This month's focus: Do good things this month

<!-- personal-goals-cli monthly -->

# Other Goals:

<!-- personal-goals-cli other -->
```

(notice the HTML comments; those won't show up on GitHub)

Now, rather than replacing the whole README when a goal is added/changed/removed, it just looks for the marker and adds/changes/removes the goal there. That way, I can change the format, edit the top part of the README or add more information add the bottom but the goal setting will still work!

What do you think?

**Comment by modernkd** [comment]
I like the idea. Would it be better to have a template.md that it can parse from so you can change the format at any point and on next render, it will use that format?

**Comment by modernkd** [comment]
Or stick with this, you should be able to edit the readme at any time and it will look for those comments before writing anything new

**Comment by mxstbr** [comment]
I kinda dislike that because it means I have an additional file in my repo that I don't really need. I guess I could not check it into VCS but then I'd have to copy and paste it between computers.

I'd much prefer if I could just go in and edit the README however I want AS LONG AS the markers are there.

**Comment by mxstbr** [comment]
> Or stick with this, you should be able to edit the readme at any time and it will look for those comments before writing anything new

That sounds very great to me. Could also make the markers more explicit, something like `<!-- DO NOT TOUCH THIS COMMENT, PERSONAL GOALS CLI NEEDS IT TO KNOW WHERE WEEKLY GOALS GO -->` or something haha

**Comment by modernkd** [comment]
I definitely don't want to clutter a repo. I think having everything happen within the README is the way to go. It could theoretically overwrite the comments and store the current template in the config.

**Comment by mxstbr** [comment]
I guess, but then what if I change it again? That just sounds like more trouble than is worth it rather than just leaving the markers there

**Comment by modernkd** [comment]
If you change it, it would update the config, but if you wanted to use it across machines, it wouldn't work out, so leaving the comments in would be best. I think it would need a beginning and end comment so it knows what it can throw out on each render

**Comment by mxstbr** [comment]
That sounds good to me!

**Comment by modernkd** [comment]
Thanks so much for helping me think through this 😄

**Comment by mxstbr** [comment]
No worries, can't wait for this to land!

**Comment by modernkd** [comment]
Please let me know what you think and if there are any other improvements that can be made!
